# Generated by Django 4.2.3 on 2024-11-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='class_period',
            field=models.IntegerField(choices=[(1, '第一节课 (8:00 - 10:00)'), (2, '第二节课 (10:00 - 12:00)'), (3, '第三节课 (14:00 - 16:00)'), (4, '第四节课 (16:00 - 18:00)')], default=1, verbose_name='上课节次'),
        ),
        migrations.AddField(
            model_name='course',
            name='day_of_week',
            field=models.IntegerField(choices=[(1, '周一'), (2, '周二'), (3, '周三'), (4, '周四'), (5, '周五'), (6, '周六'), (7, '周日')], default=1, verbose_name='上课日'),
        ),
    ]
